DATASET:
  TRAIN: "/home/zcf/FastestDet-main/SAU/train.txt"
  VAL: "/home/zcf/FastestDet-main/SAU/val.txt"
  NAMES: "configs/armor.names"
MODEL:
  NC: 9
  NPTS: 4 
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 32
  END_EPOCH: 500
  MILESTIONES:
    - 50
    - 100
    - 150
    
